---
- name: Test
  hosts: localhost
  tasks:
    - name: Deploy Operators
      ansible.builtin.include_role: 
        name: ansible.ocp.operator
      vars:
        namespaces:
          - name: aap
        operators:
          - name: openshift-gitops-operator
            namespace: openshift-operators
            channel: gitops-1.12
            source: redhat-operators
            sourcenamespace: openshift-marketplace
            clusterwide: true
          - name: ansible-automation-platform-operator
            namespace: aap
            channel: stable-2.4-cluster-scoped
            source: redhat-operators
            sourcenamespace: openshift-marketplace
            clusterwide: false

    - name: Deploy Applications
      ansible.builtin.include_role: 
        name: ansible.ocp.argocd
      vars:
        namespaces:
          - name: aap
        resources_url: https://github.com/zaskan/openshift.git
        target_revision: main
        resources_path: "manifests/aap/"

    - name: Configure Automation Controller
      ansible.builtin.include_role: 
        name: ansible_automation_platform.casc.controller
      vars:
        controller_vars_dir: vars/controller
