credentials:
  - name: "Red Hat Ansible Automation Platform Credential"
    desc: "Red Hat Ansible Automation Platform Credential"
    org: Default
    type: "Red Hat Ansible Automation Platform"
    inputs:
      host: "{{ controller_host }}"
      username: "{{ controller_user }}"
      password: "{{ controller_password }}"
  - name: "Red Hat Event-Driven Ansible Credential"
    desc: "Red Hat Event-Driven Ansible Credential"
    org: Default
    type: "Red Hat Event-Driven Ansible"
    inputs:
      eda_host: "{{ eda_host }}"
      eda_username: "admin"
      eda_password: "{{ eda_password }}"
  - name: "OpenShift API Bearer Token"
    desc: "OpenShift API Bearer Token"
    org: Default
    type: "OpenShift or Kubernetes API Bearer Token"
    inputs:
      host: "{{ openshift_api }}"
      bearer_token: "{{ openshift_token }}"
  - name: "ServiceNow Credential"
    desc: "ServiceNow Credential"
    org: Default
    type: "ServiceNow"
    inputs:
      sn_host: "{{ snow_instance_host }}"
      sn_username: "{{ snow_eda_username }}"
      sn_password: "{{ snow_eda_password }}"
  - name: "Gitea Credential"
    desc: "Gitea Credential"
    org: Default
    type: "Gitea"
    inputs:
      gitea_email: "{{ gitea_email }}"
      gitea_username: "{{ gitea_username }}"
      gitea_password: "{{ gitea_password }}"
  - name: "Amazon Web Services Credential"
    desc: "Amazon Web Services Credential"
    org: Default
    type: "Amazon Web Services"
    inputs:
      username: "{{ aws_access_key }}"
      password: "{{ aws_secret_key }}"
  - name: "Amazon Web Services Key Pair"
    desc: "Amazon Web Services Key Pair"
    org: Default
    type: "Machine"
    inputs:
      username: "ec2-user"
      ssh_key_data: "{{ lookup('ansible.builtin.file', aws_key_priv_rsa_path) }}"
